info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version} 

spring:
  data:
    mongodb:
      host: localhost
      database: msadb
      port: 27017

   
server:
  port: 9082


#Give IP address
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.80.31:8761/eureka/